openapi: 3.0.0
info: 
    title: Authentication System
    description: Here user use this API'S Docs to be registered and login for any application.
    version: 1.0.0

servers:
  - url: http://localhost:4200/
    description: This is a localserver URL for run backend Application.
  - url: https://my-authentication-system.herokuapp.com/
    description: This is a Live server URL for run backend Application.

paths:
    /register: